//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Loowoo.Land.OA.Service.Missive.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JSWJSoap", Namespace="http://tempuri.org/")]
    public partial class JSWJ : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback js_wj2OperationCompleted;
        
        private System.Threading.SendOrPostCallback js_wjOperationCompleted;
        
        private System.Threading.SendOrPostCallback js_wj_notifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback sjdxOperationCompleted;
        
        private System.Threading.SendOrPostCallback wj_fjOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFile_DWJOperationCompleted;
        
        private System.Threading.SendOrPostCallback lcOperationCompleted;
        
        private System.Threading.SendOrPostCallback jsjbggOperationCompleted;
        
        private System.Threading.SendOrPostCallback jsjbggfjOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSJHMOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateJSWJBTOperationCompleted;
        
        private System.Threading.SendOrPostCallback cswj_swfw_WbOperationCompleted;
        
        private System.Threading.SendOrPostCallback cswj_xwgg_WbOperationCompleted;
        
        private System.Threading.SendOrPostCallback wj_fj_qzfOperationCompleted;
        
        private System.Threading.SendOrPostCallback js_wj_qzfOperationCompleted;
        
        private System.Threading.SendOrPostCallback jsxwgg_zbOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public JSWJ() {
            this.Url = global::Loowoo.Land.OA.Service.Missive.Properties.Settings.Default.Loowoo_Land_OA_Service_Missive_WebReference_JSWJ;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event js_wj2CompletedEventHandler js_wj2Completed;
        
        /// <remarks/>
        public event js_wjCompletedEventHandler js_wjCompleted;
        
        /// <remarks/>
        public event js_wj_notifyCompletedEventHandler js_wj_notifyCompleted;
        
        /// <remarks/>
        public event sjdxCompletedEventHandler sjdxCompleted;
        
        /// <remarks/>
        public event wj_fjCompletedEventHandler wj_fjCompleted;
        
        /// <remarks/>
        public event getFileCompletedEventHandler getFileCompleted;
        
        /// <remarks/>
        public event getFile_DWJCompletedEventHandler getFile_DWJCompleted;
        
        /// <remarks/>
        public event lcCompletedEventHandler lcCompleted;
        
        /// <remarks/>
        public event jsjbggCompletedEventHandler jsjbggCompleted;
        
        /// <remarks/>
        public event jsjbggfjCompletedEventHandler jsjbggfjCompleted;
        
        /// <remarks/>
        public event getSJHMCompletedEventHandler getSJHMCompleted;
        
        /// <remarks/>
        public event updateJSWJBTCompletedEventHandler updateJSWJBTCompleted;
        
        /// <remarks/>
        public event cswj_swfw_WbCompletedEventHandler cswj_swfw_WbCompleted;
        
        /// <remarks/>
        public event cswj_xwgg_WbCompletedEventHandler cswj_xwgg_WbCompleted;
        
        /// <remarks/>
        public event wj_fj_qzfCompletedEventHandler wj_fj_qzfCompleted;
        
        /// <remarks/>
        public event js_wj_qzfCompletedEventHandler js_wj_qzfCompleted;
        
        /// <remarks/>
        public event jsxwgg_zbCompletedEventHandler jsxwgg_zbCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/2", RequestElementName="2", RequestNamespace="http://tempuri.org/", ResponseElementName="2Response", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("2Result")]
        public string js_wj2(
                    string id, 
                    string mmjb, 
                    string jjcd, 
                    string lwbh, 
                    string lsh, 
                    string bt, 
                    string wjzl, 
                    string lwdw, 
                    string ztc, 
                    string zy, 
                    string cjrid, 
                    string dwid, 
                    string qsrq, 
                    string lylb, 
                    string fromXxid, 
                    string fromWebServicePath) {
            object[] results = this.Invoke("js_wj2", new object[] {
                        id,
                        mmjb,
                        jjcd,
                        lwbh,
                        lsh,
                        bt,
                        wjzl,
                        lwdw,
                        ztc,
                        zy,
                        cjrid,
                        dwid,
                        qsrq,
                        lylb,
                        fromXxid,
                        fromWebServicePath});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void js_wj2Async(
                    string id, 
                    string mmjb, 
                    string jjcd, 
                    string lwbh, 
                    string lsh, 
                    string bt, 
                    string wjzl, 
                    string lwdw, 
                    string ztc, 
                    string zy, 
                    string cjrid, 
                    string dwid, 
                    string qsrq, 
                    string lylb, 
                    string fromXxid, 
                    string fromWebServicePath) {
            this.js_wj2Async(id, mmjb, jjcd, lwbh, lsh, bt, wjzl, lwdw, ztc, zy, cjrid, dwid, qsrq, lylb, fromXxid, fromWebServicePath, null);
        }
        
        /// <remarks/>
        public void js_wj2Async(
                    string id, 
                    string mmjb, 
                    string jjcd, 
                    string lwbh, 
                    string lsh, 
                    string bt, 
                    string wjzl, 
                    string lwdw, 
                    string ztc, 
                    string zy, 
                    string cjrid, 
                    string dwid, 
                    string qsrq, 
                    string lylb, 
                    string fromXxid, 
                    string fromWebServicePath, 
                    object userState) {
            if ((this.js_wj2OperationCompleted == null)) {
                this.js_wj2OperationCompleted = new System.Threading.SendOrPostCallback(this.Onjs_wj2OperationCompleted);
            }
            this.InvokeAsync("js_wj2", new object[] {
                        id,
                        mmjb,
                        jjcd,
                        lwbh,
                        lsh,
                        bt,
                        wjzl,
                        lwdw,
                        ztc,
                        zy,
                        cjrid,
                        dwid,
                        qsrq,
                        lylb,
                        fromXxid,
                        fromWebServicePath}, this.js_wj2OperationCompleted, userState);
        }
        
        private void Onjs_wj2OperationCompleted(object arg) {
            if ((this.js_wj2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.js_wj2Completed(this, new js_wj2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/1", RequestElementName="1", RequestNamespace="http://tempuri.org/", ResponseElementName="1Response", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("1Result")]
        public string js_wj(string id, string mmjb, string jjcd, string lwbh, string lsh, string bt, string wjzl, string lwdw, string ztc, string zy, string cjrid, string dwid, string qsrq, string lylb) {
            object[] results = this.Invoke("js_wj", new object[] {
                        id,
                        mmjb,
                        jjcd,
                        lwbh,
                        lsh,
                        bt,
                        wjzl,
                        lwdw,
                        ztc,
                        zy,
                        cjrid,
                        dwid,
                        qsrq,
                        lylb});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void js_wjAsync(string id, string mmjb, string jjcd, string lwbh, string lsh, string bt, string wjzl, string lwdw, string ztc, string zy, string cjrid, string dwid, string qsrq, string lylb) {
            this.js_wjAsync(id, mmjb, jjcd, lwbh, lsh, bt, wjzl, lwdw, ztc, zy, cjrid, dwid, qsrq, lylb, null);
        }
        
        /// <remarks/>
        public void js_wjAsync(string id, string mmjb, string jjcd, string lwbh, string lsh, string bt, string wjzl, string lwdw, string ztc, string zy, string cjrid, string dwid, string qsrq, string lylb, object userState) {
            if ((this.js_wjOperationCompleted == null)) {
                this.js_wjOperationCompleted = new System.Threading.SendOrPostCallback(this.Onjs_wjOperationCompleted);
            }
            this.InvokeAsync("js_wj", new object[] {
                        id,
                        mmjb,
                        jjcd,
                        lwbh,
                        lsh,
                        bt,
                        wjzl,
                        lwdw,
                        ztc,
                        zy,
                        cjrid,
                        dwid,
                        qsrq,
                        lylb}, this.js_wjOperationCompleted, userState);
        }
        
        private void Onjs_wjOperationCompleted(object arg) {
            if ((this.js_wjCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.js_wjCompleted(this, new js_wjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/3", RequestElementName="3", RequestNamespace="http://tempuri.org/", ResponseElementName="3Response", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("3Result")]
        public string js_wj_notify(string id, string mmjb, string jjcd, string lwbh, string lsh, string bt, string wjzl, string lwdw, string ztc, string zy, string cjrid, string dwid, string qsrq, string lylb) {
            object[] results = this.Invoke("js_wj_notify", new object[] {
                        id,
                        mmjb,
                        jjcd,
                        lwbh,
                        lsh,
                        bt,
                        wjzl,
                        lwdw,
                        ztc,
                        zy,
                        cjrid,
                        dwid,
                        qsrq,
                        lylb});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void js_wj_notifyAsync(string id, string mmjb, string jjcd, string lwbh, string lsh, string bt, string wjzl, string lwdw, string ztc, string zy, string cjrid, string dwid, string qsrq, string lylb) {
            this.js_wj_notifyAsync(id, mmjb, jjcd, lwbh, lsh, bt, wjzl, lwdw, ztc, zy, cjrid, dwid, qsrq, lylb, null);
        }
        
        /// <remarks/>
        public void js_wj_notifyAsync(string id, string mmjb, string jjcd, string lwbh, string lsh, string bt, string wjzl, string lwdw, string ztc, string zy, string cjrid, string dwid, string qsrq, string lylb, object userState) {
            if ((this.js_wj_notifyOperationCompleted == null)) {
                this.js_wj_notifyOperationCompleted = new System.Threading.SendOrPostCallback(this.Onjs_wj_notifyOperationCompleted);
            }
            this.InvokeAsync("js_wj_notify", new object[] {
                        id,
                        mmjb,
                        jjcd,
                        lwbh,
                        lsh,
                        bt,
                        wjzl,
                        lwdw,
                        ztc,
                        zy,
                        cjrid,
                        dwid,
                        qsrq,
                        lylb}, this.js_wj_notifyOperationCompleted, userState);
        }
        
        private void Onjs_wj_notifyOperationCompleted(object arg) {
            if ((this.js_wj_notifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.js_wj_notifyCompleted(this, new js_wj_notifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sjdx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sjdx(string dxnr, string dwid) {
            object[] results = this.Invoke("sjdx", new object[] {
                        dxnr,
                        dwid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sjdxAsync(string dxnr, string dwid) {
            this.sjdxAsync(dxnr, dwid, null);
        }
        
        /// <remarks/>
        public void sjdxAsync(string dxnr, string dwid, object userState) {
            if ((this.sjdxOperationCompleted == null)) {
                this.sjdxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsjdxOperationCompleted);
            }
            this.InvokeAsync("sjdx", new object[] {
                        dxnr,
                        dwid}, this.sjdxOperationCompleted, userState);
        }
        
        private void OnsjdxOperationCompleted(object arg) {
            if ((this.sjdxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sjdxCompleted(this, new sjdxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wj_fj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wj_fj(string ftableid, string fjmc, string fjpath, string lytype) {
            object[] results = this.Invoke("wj_fj", new object[] {
                        ftableid,
                        fjmc,
                        fjpath,
                        lytype});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wj_fjAsync(string ftableid, string fjmc, string fjpath, string lytype) {
            this.wj_fjAsync(ftableid, fjmc, fjpath, lytype, null);
        }
        
        /// <remarks/>
        public void wj_fjAsync(string ftableid, string fjmc, string fjpath, string lytype, object userState) {
            if ((this.wj_fjOperationCompleted == null)) {
                this.wj_fjOperationCompleted = new System.Threading.SendOrPostCallback(this.Onwj_fjOperationCompleted);
            }
            this.InvokeAsync("wj_fj", new object[] {
                        ftableid,
                        fjmc,
                        fjpath,
                        lytype}, this.wj_fjOperationCompleted, userState);
        }
        
        private void Onwj_fjOperationCompleted(object arg) {
            if ((this.wj_fjCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wj_fjCompleted(this, new wj_fjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getFile([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] file, string fjmc, string newid) {
            object[] results = this.Invoke("getFile", new object[] {
                        file,
                        fjmc,
                        newid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getFileAsync(byte[] file, string fjmc, string newid) {
            this.getFileAsync(file, fjmc, newid, null);
        }
        
        /// <remarks/>
        public void getFileAsync(byte[] file, string fjmc, string newid, object userState) {
            if ((this.getFileOperationCompleted == null)) {
                this.getFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFileOperationCompleted);
            }
            this.InvokeAsync("getFile", new object[] {
                        file,
                        fjmc,
                        newid}, this.getFileOperationCompleted, userState);
        }
        
        private void OngetFileOperationCompleted(object arg) {
            if ((this.getFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFileCompleted(this, new getFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getFile_DWJ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getFile_DWJ([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] file, string fjmc, string newid, bool ifCreate) {
            object[] results = this.Invoke("getFile_DWJ", new object[] {
                        file,
                        fjmc,
                        newid,
                        ifCreate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getFile_DWJAsync(byte[] file, string fjmc, string newid, bool ifCreate) {
            this.getFile_DWJAsync(file, fjmc, newid, ifCreate, null);
        }
        
        /// <remarks/>
        public void getFile_DWJAsync(byte[] file, string fjmc, string newid, bool ifCreate, object userState) {
            if ((this.getFile_DWJOperationCompleted == null)) {
                this.getFile_DWJOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFile_DWJOperationCompleted);
            }
            this.InvokeAsync("getFile_DWJ", new object[] {
                        file,
                        fjmc,
                        newid,
                        ifCreate}, this.getFile_DWJOperationCompleted, userState);
        }
        
        private void OngetFile_DWJOperationCompleted(object arg) {
            if ((this.getFile_DWJCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFile_DWJCompleted(this, new getFile_DWJCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/lc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string lc(string wjxxid) {
            object[] results = this.Invoke("lc", new object[] {
                        wjxxid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void lcAsync(string wjxxid) {
            this.lcAsync(wjxxid, null);
        }
        
        /// <remarks/>
        public void lcAsync(string wjxxid, object userState) {
            if ((this.lcOperationCompleted == null)) {
                this.lcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlcOperationCompleted);
            }
            this.InvokeAsync("lc", new object[] {
                        wjxxid}, this.lcOperationCompleted, userState);
        }
        
        private void OnlcOperationCompleted(object arg) {
            if ((this.lcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lcCompleted(this, new lcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/jsjbgg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string jsjbgg(string xxid, string title, string contents, string fbr, string jsdwid, string lylb) {
            object[] results = this.Invoke("jsjbgg", new object[] {
                        xxid,
                        title,
                        contents,
                        fbr,
                        jsdwid,
                        lylb});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void jsjbggAsync(string xxid, string title, string contents, string fbr, string jsdwid, string lylb) {
            this.jsjbggAsync(xxid, title, contents, fbr, jsdwid, lylb, null);
        }
        
        /// <remarks/>
        public void jsjbggAsync(string xxid, string title, string contents, string fbr, string jsdwid, string lylb, object userState) {
            if ((this.jsjbggOperationCompleted == null)) {
                this.jsjbggOperationCompleted = new System.Threading.SendOrPostCallback(this.OnjsjbggOperationCompleted);
            }
            this.InvokeAsync("jsjbgg", new object[] {
                        xxid,
                        title,
                        contents,
                        fbr,
                        jsdwid,
                        lylb}, this.jsjbggOperationCompleted, userState);
        }
        
        private void OnjsjbggOperationCompleted(object arg) {
            if ((this.jsjbggCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.jsjbggCompleted(this, new jsjbggCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/jsjbggfj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string jsjbggfj(string ftableid, string fjmc, string fjpath) {
            object[] results = this.Invoke("jsjbggfj", new object[] {
                        ftableid,
                        fjmc,
                        fjpath});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void jsjbggfjAsync(string ftableid, string fjmc, string fjpath) {
            this.jsjbggfjAsync(ftableid, fjmc, fjpath, null);
        }
        
        /// <remarks/>
        public void jsjbggfjAsync(string ftableid, string fjmc, string fjpath, object userState) {
            if ((this.jsjbggfjOperationCompleted == null)) {
                this.jsjbggfjOperationCompleted = new System.Threading.SendOrPostCallback(this.OnjsjbggfjOperationCompleted);
            }
            this.InvokeAsync("jsjbggfj", new object[] {
                        ftableid,
                        fjmc,
                        fjpath}, this.jsjbggfjOperationCompleted, userState);
        }
        
        private void OnjsjbggfjOperationCompleted(object arg) {
            if ((this.jsjbggfjCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.jsjbggfjCompleted(this, new jsjbggfjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSJHM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getSJHM(string dwid, string lb) {
            object[] results = this.Invoke("getSJHM", new object[] {
                        dwid,
                        lb});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSJHMAsync(string dwid, string lb) {
            this.getSJHMAsync(dwid, lb, null);
        }
        
        /// <remarks/>
        public void getSJHMAsync(string dwid, string lb, object userState) {
            if ((this.getSJHMOperationCompleted == null)) {
                this.getSJHMOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSJHMOperationCompleted);
            }
            this.InvokeAsync("getSJHM", new object[] {
                        dwid,
                        lb}, this.getSJHMOperationCompleted, userState);
        }
        
        private void OngetSJHMOperationCompleted(object arg) {
            if ((this.getSJHMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSJHMCompleted(this, new getSJHMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateJSWJBT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string updateJSWJBT(string dwid, string bt) {
            object[] results = this.Invoke("updateJSWJBT", new object[] {
                        dwid,
                        bt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateJSWJBTAsync(string dwid, string bt) {
            this.updateJSWJBTAsync(dwid, bt, null);
        }
        
        /// <remarks/>
        public void updateJSWJBTAsync(string dwid, string bt, object userState) {
            if ((this.updateJSWJBTOperationCompleted == null)) {
                this.updateJSWJBTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateJSWJBTOperationCompleted);
            }
            this.InvokeAsync("updateJSWJBT", new object[] {
                        dwid,
                        bt}, this.updateJSWJBTOperationCompleted, userState);
        }
        
        private void OnupdateJSWJBTOperationCompleted(object arg) {
            if ((this.updateJSWJBTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateJSWJBTCompleted(this, new updateJSWJBTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cswj_swfw_Wb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string cswj_swfw_Wb(string infoStr, string zwStr, string fjStr, string fromWebServicePath, string jsdwid, string newid, string ly) {
            object[] results = this.Invoke("cswj_swfw_Wb", new object[] {
                        infoStr,
                        zwStr,
                        fjStr,
                        fromWebServicePath,
                        jsdwid,
                        newid,
                        ly});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cswj_swfw_WbAsync(string infoStr, string zwStr, string fjStr, string fromWebServicePath, string jsdwid, string newid, string ly) {
            this.cswj_swfw_WbAsync(infoStr, zwStr, fjStr, fromWebServicePath, jsdwid, newid, ly, null);
        }
        
        /// <remarks/>
        public void cswj_swfw_WbAsync(string infoStr, string zwStr, string fjStr, string fromWebServicePath, string jsdwid, string newid, string ly, object userState) {
            if ((this.cswj_swfw_WbOperationCompleted == null)) {
                this.cswj_swfw_WbOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncswj_swfw_WbOperationCompleted);
            }
            this.InvokeAsync("cswj_swfw_Wb", new object[] {
                        infoStr,
                        zwStr,
                        fjStr,
                        fromWebServicePath,
                        jsdwid,
                        newid,
                        ly}, this.cswj_swfw_WbOperationCompleted, userState);
        }
        
        private void Oncswj_swfw_WbOperationCompleted(object arg) {
            if ((this.cswj_swfw_WbCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cswj_swfw_WbCompleted(this, new cswj_swfw_WbCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cswj_xwgg_Wb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string cswj_xwgg_Wb(string infoStr, string fjStr, string jsdwid, string newid, string ly) {
            object[] results = this.Invoke("cswj_xwgg_Wb", new object[] {
                        infoStr,
                        fjStr,
                        jsdwid,
                        newid,
                        ly});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cswj_xwgg_WbAsync(string infoStr, string fjStr, string jsdwid, string newid, string ly) {
            this.cswj_xwgg_WbAsync(infoStr, fjStr, jsdwid, newid, ly, null);
        }
        
        /// <remarks/>
        public void cswj_xwgg_WbAsync(string infoStr, string fjStr, string jsdwid, string newid, string ly, object userState) {
            if ((this.cswj_xwgg_WbOperationCompleted == null)) {
                this.cswj_xwgg_WbOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncswj_xwgg_WbOperationCompleted);
            }
            this.InvokeAsync("cswj_xwgg_Wb", new object[] {
                        infoStr,
                        fjStr,
                        jsdwid,
                        newid,
                        ly}, this.cswj_xwgg_WbOperationCompleted, userState);
        }
        
        private void Oncswj_xwgg_WbOperationCompleted(object arg) {
            if ((this.cswj_xwgg_WbCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cswj_xwgg_WbCompleted(this, new cswj_xwgg_WbCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wj_fj_qzf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wj_fj_qzf(string ftableid, string fjmc, string fjpath, string lytype) {
            object[] results = this.Invoke("wj_fj_qzf", new object[] {
                        ftableid,
                        fjmc,
                        fjpath,
                        lytype});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wj_fj_qzfAsync(string ftableid, string fjmc, string fjpath, string lytype) {
            this.wj_fj_qzfAsync(ftableid, fjmc, fjpath, lytype, null);
        }
        
        /// <remarks/>
        public void wj_fj_qzfAsync(string ftableid, string fjmc, string fjpath, string lytype, object userState) {
            if ((this.wj_fj_qzfOperationCompleted == null)) {
                this.wj_fj_qzfOperationCompleted = new System.Threading.SendOrPostCallback(this.Onwj_fj_qzfOperationCompleted);
            }
            this.InvokeAsync("wj_fj_qzf", new object[] {
                        ftableid,
                        fjmc,
                        fjpath,
                        lytype}, this.wj_fj_qzfOperationCompleted, userState);
        }
        
        private void Onwj_fj_qzfOperationCompleted(object arg) {
            if ((this.wj_fj_qzfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wj_fj_qzfCompleted(this, new wj_fj_qzfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/js_wj_qzf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string js_wj_qzf(string id, string mmjb, string jjcd, string lwbh, string lsh, string bt, string wjzl, string lwdw, string ztc, string zy, string cjrid, string dwid, string qsrq, string lylb) {
            object[] results = this.Invoke("js_wj_qzf", new object[] {
                        id,
                        mmjb,
                        jjcd,
                        lwbh,
                        lsh,
                        bt,
                        wjzl,
                        lwdw,
                        ztc,
                        zy,
                        cjrid,
                        dwid,
                        qsrq,
                        lylb});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void js_wj_qzfAsync(string id, string mmjb, string jjcd, string lwbh, string lsh, string bt, string wjzl, string lwdw, string ztc, string zy, string cjrid, string dwid, string qsrq, string lylb) {
            this.js_wj_qzfAsync(id, mmjb, jjcd, lwbh, lsh, bt, wjzl, lwdw, ztc, zy, cjrid, dwid, qsrq, lylb, null);
        }
        
        /// <remarks/>
        public void js_wj_qzfAsync(string id, string mmjb, string jjcd, string lwbh, string lsh, string bt, string wjzl, string lwdw, string ztc, string zy, string cjrid, string dwid, string qsrq, string lylb, object userState) {
            if ((this.js_wj_qzfOperationCompleted == null)) {
                this.js_wj_qzfOperationCompleted = new System.Threading.SendOrPostCallback(this.Onjs_wj_qzfOperationCompleted);
            }
            this.InvokeAsync("js_wj_qzf", new object[] {
                        id,
                        mmjb,
                        jjcd,
                        lwbh,
                        lsh,
                        bt,
                        wjzl,
                        lwdw,
                        ztc,
                        zy,
                        cjrid,
                        dwid,
                        qsrq,
                        lylb}, this.js_wj_qzfOperationCompleted, userState);
        }
        
        private void Onjs_wj_qzfOperationCompleted(object arg) {
            if ((this.js_wj_qzfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.js_wj_qzfCompleted(this, new js_wj_qzfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/jsxwgg_zb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string jsxwgg_zb(string xxid, string lmtype, string bt, string fbrid, string fbrxm, string fbsj, string nr, string jsdwid, string czlx, string wjly) {
            object[] results = this.Invoke("jsxwgg_zb", new object[] {
                        xxid,
                        lmtype,
                        bt,
                        fbrid,
                        fbrxm,
                        fbsj,
                        nr,
                        jsdwid,
                        czlx,
                        wjly});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void jsxwgg_zbAsync(string xxid, string lmtype, string bt, string fbrid, string fbrxm, string fbsj, string nr, string jsdwid, string czlx, string wjly) {
            this.jsxwgg_zbAsync(xxid, lmtype, bt, fbrid, fbrxm, fbsj, nr, jsdwid, czlx, wjly, null);
        }
        
        /// <remarks/>
        public void jsxwgg_zbAsync(string xxid, string lmtype, string bt, string fbrid, string fbrxm, string fbsj, string nr, string jsdwid, string czlx, string wjly, object userState) {
            if ((this.jsxwgg_zbOperationCompleted == null)) {
                this.jsxwgg_zbOperationCompleted = new System.Threading.SendOrPostCallback(this.Onjsxwgg_zbOperationCompleted);
            }
            this.InvokeAsync("jsxwgg_zb", new object[] {
                        xxid,
                        lmtype,
                        bt,
                        fbrid,
                        fbrxm,
                        fbsj,
                        nr,
                        jsdwid,
                        czlx,
                        wjly}, this.jsxwgg_zbOperationCompleted, userState);
        }
        
        private void Onjsxwgg_zbOperationCompleted(object arg) {
            if ((this.jsxwgg_zbCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.jsxwgg_zbCompleted(this, new jsxwgg_zbCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void js_wj2CompletedEventHandler(object sender, js_wj2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class js_wj2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal js_wj2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void js_wjCompletedEventHandler(object sender, js_wjCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class js_wjCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal js_wjCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void js_wj_notifyCompletedEventHandler(object sender, js_wj_notifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class js_wj_notifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal js_wj_notifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void sjdxCompletedEventHandler(object sender, sjdxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sjdxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sjdxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void wj_fjCompletedEventHandler(object sender, wj_fjCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wj_fjCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wj_fjCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getFileCompletedEventHandler(object sender, getFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getFile_DWJCompletedEventHandler(object sender, getFile_DWJCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFile_DWJCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFile_DWJCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void lcCompletedEventHandler(object sender, lcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal lcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void jsjbggCompletedEventHandler(object sender, jsjbggCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class jsjbggCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal jsjbggCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void jsjbggfjCompletedEventHandler(object sender, jsjbggfjCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class jsjbggfjCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal jsjbggfjCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getSJHMCompletedEventHandler(object sender, getSJHMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSJHMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSJHMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void updateJSWJBTCompletedEventHandler(object sender, updateJSWJBTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateJSWJBTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateJSWJBTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void cswj_swfw_WbCompletedEventHandler(object sender, cswj_swfw_WbCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cswj_swfw_WbCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cswj_swfw_WbCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void cswj_xwgg_WbCompletedEventHandler(object sender, cswj_xwgg_WbCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cswj_xwgg_WbCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cswj_xwgg_WbCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void wj_fj_qzfCompletedEventHandler(object sender, wj_fj_qzfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wj_fj_qzfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wj_fj_qzfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void js_wj_qzfCompletedEventHandler(object sender, js_wj_qzfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class js_wj_qzfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal js_wj_qzfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void jsxwgg_zbCompletedEventHandler(object sender, jsxwgg_zbCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class jsxwgg_zbCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal jsxwgg_zbCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591